### ISSUE TITLE
TypeError in phoenix_precision with only 3 args.

### ISSUE THREAD

**Issue by jason-neal** [jason-neal/eniric#132]
**Describe the bug**
TypeError in phoenix_precision with only 3 args.

**To Reproduce**
```
 phoenix_precision.py -m 2800 -l 4.5 -m 0.0
Traceback (most recent call last):
  File "/home/jneal/anaconda3/envs/eniric/bin/phoenix_precision.py", line 7, in                     <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/jneal/Phd/Codes/eniric/scripts/phoenix_precision.py", line 455, in                     <module>
    models_list = itertools.product(args.temp, args.logg, args.metal, args.alpha                    )
TypeError: 'NoneType' object is not iterable

```

**Comment by jason-neal** [comment]
This command was broken in that it has `-m` flag twice and no `-t` flag.  The type error has been resolved using  default temperature of 3900 K.

The last -m overwrote the first incorrect one.
