### ISSUE TITLE
Appveyor build not correct

### ISSUE THREAD

**Issue by jason-neal** [jason-neal/eniric#64]
Failing to make the data for testing.
```

move tests\config.yaml config.yaml
        1 file(s) moved.
%PYTH
l config.yaml
        1 file(s) moved.
%PYTHON%\python.exe bin\mk_travis_data.py
Traceback (most recent call last):
  File "bin/prepare_data.py", line 17, in <module>
    import numpy as np
ImportError: No module named numpy
The system cannot find the path specified.
The system cannot find ON%\python.exe bin\mk_travis_data.py
Traceback (most recent call last):
  File "bin/prepare_data.py", line 17, in <module>
    import numpy as np
ImportError: No module named numpy
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[('data', ['atmmodel', 'PHOENIX-ACES_spectra', 'precision', 'Published_Results', 'test_data'], ['old_fluxnorm_precision_results_2017.txt']), ('data\\atmmodel', [], ['Average_TAPAS_2014_GAP.txt', 'Average_TAPAS_2014_H.txt', 'Average_TAPAS_2014_H_bary.txt', 'Average_TAPAS_2014_J.txt', 'Average_TAPAS_2014_J_bary.txt', 'Average_TAPAS_2014_K.txt', 'Average_TAPAS_2014_K_bary.txt', 'Average_TAPAS_2014_VIS.txt', 'Average_TAPAS_2014_Y.txt', 'Average_TAPAS_2014_Y_bary.txt', 'Average_TAPAS_2014_Z.txt', 'Average_TAPAS_2014_Z_bary.txt']), ('data\\PHOENIX-ACES_spectra', [], ['lte02600-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave.dat', 'lte02800-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave.dat', 'lte03500-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave.dat', 'lte03900-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave.dat', 'WAVE_PHOENIX-ACES-AGSS-COND-2011.fits']), ('data\\precision', [], ['nir_precision_2017_2017_ref_band-J_snr-100-for_claire18_9_2017_.txt', 'nir_precision_2017_ref_band-self_snr-100for_claire18_9_2017.txt', 'precision_data_paper2015.txt', 'precision_results_2017.txt']), ('data\\Published_Results', ['resampled', 'results'], []), ('data\\Published_Results\\resampled', [], ['Spectrum_M0-PHOENIX-ACES_Yband_vsini1.0_R100k_res3.txt', 'Spectrum_M0-PHOENIX-ACES_Yband_vsini10.0_R100k_res3.txt', 'Spectrum_M0-PHOENIX-ACES_Yband_vsini5.0_R100k_res3.txt']), ('data\\Published_Results\\results', [], ['Spectrum_M0-PHOENIX-ACES_Yband_vsini1.0_R100k.txt', 'Spectrum_M0-PHOENIX-ACES_Yband_vsini10.0_R100k.txt', 'Spectrum_M0-PHOENIX-ACES_Yband_vsini5.0_R100k.txt']), ('data\\test_data', ['atmmodel', 'PHOENIX-raw', 'resampled'], ['GAP_band_test_sample_lte03900-PHOENIX-ACES.dat', 'H_band_test_sample_lte03900-PHOENIX-ACES.dat', 'J_band_test_sample_lte03900-PHOENIX-ACES.dat', 'K_band_test_sample_lte03900-PHOENIX-ACES.dat', 'Sample_input_phoenix.dat', 'sample_lte03900-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave.dat', 'sample_lte03900-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes_wave_photon.dat', 'Sample_resampled_spectrum_res3.txt', 'Sample_results_spectrum.txt', 'VIS_band_test_sample_lte03900-PHOENIX-ACES.dat', 'Y_band_test_sample_lte03900-PHOENIX-ACES.dat', 'Z_band_test_sample_lte03900-PHOENIX-ACES.dat']), ('data\\test_data\\atmmodel', [], ['Average_TAPAS_2014_H_bary.txt', 'Average_TAPAS_2014_J_bary.txt', 'Average_TAPAS_2014_K_bary.txt', 'Average_TAPAS_2014_Y_bary.txt', 'Average_TAPAS_2014_Z_bary.txt']), ('data\\test_data\\PHOENIX-raw', ['Z-0.0'], ['WAVE_PHOENIX-ACES-AGSS-COND-2011.fits']), ('data\\test_data\\PHOENIX-raw\\Z-0.0', [], ['lte02600-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits', 'lte02800-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits', 'lte03500-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits', 'lte03900-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits']), ('data\\test_data\\resampled', [], ['Spectrum_M0-PHOENIX-ACES_Jband_vsini1.0_R100k_res3.txt', 'Spectrum_M0-PHOENIX-ACES_Kband_vsini1.0_R100k_res3.txt'])]
```

**Comment by jason-neal** [comment]
Used `os.sep` in places, changed config. and adjust appveyor build script commands.

Finally working after 7ca3ddc52ccb1ff2076db
